# Exercises

## Exercise 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

2.3.3


## Exercise 2. How to create a 1D array?

In [7]:
print(np.ones(5, dtype=int))
print(np.ones(5))
print(np.zeros(5))
print(np.zeros(5, dtype=int))
print(np.arange(10))

[1 1 1 1 1]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 3. How to create a boolean array?

In [27]:
print(np.ones((3,3), dtype=bool))
print(np.full((3,3), True))
print(np.full(10, True).reshape(5,2))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
