# Exercises

## Exercise 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

2.3.3


## Exercise 2. How to create a 1D array?

In [7]:
print(np.ones(5, dtype=int))
print(np.ones(5))
print(np.zeros(5))
print(np.zeros(5, dtype=int))
print(np.arange(10))

[1 1 1 1 1]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 3. How to create a boolean array?

In [27]:
print(np.ones((3,3), dtype=bool))
print(np.full((3,3), True))
print(np.full(10, True).reshape(5,2))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


## Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Even numbers filter
x[x % 2 == 0]

array([0, 2, 4, 6, 8])

In [11]:
# Odd numbers filter
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

## Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [27]:
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Exercise 6. How to replace items that satisfy a condition without affecting the original array?

In [28]:
original = np.arange(10)
copy = original.copy()
copy[copy%2==0] = -1

In [29]:
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
copy

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

## Exercise 7. How to reshape an array?

In [36]:
shape = np.arange(9)
shape.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

-1 parameter in `.reshape()` function is used to automatically decide the number of rows or columns

In [49]:
np.arange(15).reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
np.arange(15).reshape(-1, 5) 


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])