# Exercises

## Exercise 1. Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)

2.3.3


## Exercise 2. How to create a 1D array?

In [7]:
print(np.ones(5, dtype=int))
print(np.ones(5))
print(np.zeros(5))
print(np.zeros(5, dtype=int))
print(np.arange(10))

[1 1 1 1 1]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 3. How to create a boolean array?

In [27]:
print(np.ones((3,3), dtype=bool))
print(np.full((3,3), True))
print(np.full(10, True).reshape(5,2))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


## Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Even numbers filter
x[x % 2 == 0]

array([0, 2, 4, 6, 8])

In [11]:
# Odd numbers filter
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

## Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [27]:
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Exercise 6. How to replace items that satisfy a condition without affecting the original array?

In [28]:
original = np.arange(10)
copy = original.copy()
copy[copy%2==0] = -1

In [29]:
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
copy

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

## Exercise 7. How to reshape an array?

In [36]:
shape = np.arange(9)
shape.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

-1 parameter in `.reshape()` function is used to automatically decide the number of rows or columns

In [49]:
np.arange(15).reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
np.arange(15).reshape(-1, 5) 


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Exercise 8. How to stack two arrays vertically?

In [5]:
arr1 = np.zeros(5, dtype=int)
arr2 = np.ones(5, dtype=int)

In [8]:
np.vstack([arr1, arr2])

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

## Exercise 9. How to stack two arrays horizontally?

In [9]:
np.hstack([arr1, arr2])

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

## Exercise 10. How to generate custom sequences in numpy without hardcoding?

In [16]:
a1 = np.arange(0,10,2)
a1

array([0, 2, 4, 6, 8])

In [17]:
a2 = np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

In [19]:
np.hstack([np.repeat(a1,2), np.tile(a2,2)])

array([0, 0, 2, 2, 4, 4, 6, 6, 8, 8, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9])

## Exercise 11. How to get the common items between two python numpy arrays?

In [3]:
a11 = np.array([1,2,3,4,5])
b11 = np.array([0,2,4,6,8])

In [4]:
np.intersect1d(a11,b11)

array([2, 4])

In [8]:
c11 = np.zeros(10, dtype=int).reshape(2, -1)
d11 = np.ones(10, dtype=int).reshape(1, -1)

In [10]:
np.intersect1d(c11, d11)

array([], dtype=int64)

`.intersect1d(x, y)` it return 1D array of common elements

## Exercise 12. How to remove from one array those items that exist in another?

In [11]:
np.setdiff1d(a11, b11)

array([1, 3, 5])

## Exercise 13. How to get the positions where elements of two arrays match?

In [15]:
z11 = np.array([1,2,3,4,5,6])
y11 = np.array([1,0,3,0,0,6])
np.where(z11==y11)

(array([0, 2, 5]),)

In [18]:
# index of even numbers
np.where(z11%2==0)

(array([1, 3, 5]),)

## Exercise 14. How to extract all numbers between a given range from a numpy array?

In [28]:
a14 = np.arange(12)
# extract 5 to 10
result = a14[(a14>=5) & (a14<=10)]
result

array([ 5,  6,  7,  8,  9, 10])

## Exercise 15. How to make a python function that handles scalars to work on numpy arrays?

In [2]:
def result(x, y):
    maximum = [max(i, j) for i, j in zip(x, y)]
    return np.array(maximum)
a = np.array([5,6,9,7,3,1,2,4,6,8])
b = np.array([6,9,7,6,2,1,7,3,8,6])
result(a,b)

array([6, 9, 9, 7, 3, 1, 7, 4, 8, 8])

## Exercise 16. How to swap two columns in a 2d numpy array?

In [16]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,0,1,2]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [18]:
a[:,[1,0,2,3]]

array([[2, 1, 3, 4],
       [6, 5, 7, 8],
       [0, 9, 1, 2]])

## Exercise 17. How to swap two rows in a 2d numpy array?

In [20]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [19]:
a[[1,0,2],:]

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [9, 0, 1, 2]])

## Exercise 18. How to reverse the rows of a 2D array?

In [26]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [27]:
a[::-1,:]

array([[9, 0, 1, 2],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

## Exercise 19. How to reverse the columns of a 2D array?

In [28]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [29]:
a[:,::-1]

array([[4, 3, 2, 1],
       [8, 7, 6, 5],
       [2, 1, 0, 9]])

## Exercise 20. How to create a 2D array containing random floats between 5 and 10?

In [35]:
a = np.random.uniform(5, 10, size=(2,2))
a

array([[7.84244175, 7.81487677],
       [9.6954769 , 5.76339516]])

## Exercise 21. How to print only 3 decimal places in python numpy array?

In [36]:
np.set_printoptions(precision=3)
a

array([[7.842, 7.815],
       [9.695, 5.763]])

## Exercise 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

## Exercise 23. How to limit the number of items printed in output of numpy array?

In [10]:
a = np.zeros(20, dtype=int)
np.set_printoptions(threshold=6)
a

array([0, 0, 0, ..., 0, 0, 0], shape=(20,))

## Exercise 24. How to print the full numpy array without truncating

In [12]:
a = np.ones(15, dtype=int)
np.set_printoptions(threshold=15)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Exercise 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [14]:
data = np.genfromtxt(
    'data.csv',
    delimiter = ',',
    dtype = None,
    encoding = 'utf-8',
    names = True
)
data

array([( 1, 'Alice', 23, 85, 165, 'A'), ( 2, 'Bob', 25, 90, 170, 'B'),
       ( 3, 'Charlie', 22, 78, 168, 'A'), ( 4, 'David', -1, 88, 172, 'B'),
       ( 5, 'Eva', 24, 92, 160, 'A'), ( 6, 'Frank', 26, 75, 175, 'B'),
       ( 7, 'Grace', 23, -1, 162, 'A'), ( 8, 'Hannah', 25, 85, 169, 'B'),
       ( 9, 'Ian', 24, 90, 171, 'A'), (10, 'Jane', 22, 88,  -1, 'B')],
      dtype=[('ID', '<i8'), ('Name', '<U7'), ('Age', '<i8'), ('Score', '<i8'), ('Height', '<i8'), ('Group', '<U1')])

## Exercise 26. How to extract a particular column from 1D array of tuples?

In [15]:
data["Name"]

array(['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace',
       'Hannah', 'Ian', 'Jane'], dtype='<U7')

## Exercise 27. How to convert a 1d array of tuples to a 2d numpy array?

## Exercise 28. How to compute the mean, median, standard deviation of a numpy array?

In [18]:
np.mean(data["Score"])

np.float64(77.0)

In [19]:
np.median(data["Score"])

np.float64(86.5)

In [20]:
np.std(data["Score"])

np.float64(26.4990565869806)

## Exercise 29. How to normalize an array so the values range exactly between 0 and 1?

## Exercise 30. How to compute the softmax score?

In [21]:
np.sum(data["Score"])

np.int64(770)

## Exercise 31. How to find the percentile scores of a numpy array?