# Exercises

## Exercise 1. Import numpy as np and see the version

In [2]:
import numpy as np
print(np.__version__)

2.3.3


## Exercise 2. How to create a 1D array?

In [7]:
print(np.ones(5, dtype=int))
print(np.ones(5))
print(np.zeros(5))
print(np.zeros(5, dtype=int))
print(np.arange(10))

[1 1 1 1 1]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 3. How to create a boolean array?

In [27]:
print(np.ones((3,3), dtype=bool))
print(np.full((3,3), True))
print(np.full(10, True).reshape(5,2))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


## Exercise 4. How to extract items that satisfy a given condition from 1D array?

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Even numbers filter
x[x % 2 == 0]

array([0, 2, 4, 6, 8])

In [11]:
# Odd numbers filter
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

## Exercise 5. How to replace items that satisfy a condition with another value in numpy array?

In [27]:
arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Exercise 6. How to replace items that satisfy a condition without affecting the original array?

In [28]:
original = np.arange(10)
copy = original.copy()
copy[copy%2==0] = -1

In [29]:
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
copy

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

## Exercise 7. How to reshape an array?

In [36]:
shape = np.arange(9)
shape.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

-1 parameter in `.reshape()` function is used to automatically decide the number of rows or columns

In [49]:
np.arange(15).reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
np.arange(15).reshape(-1, 5) 


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Exercise 8. How to stack two arrays vertically?

In [5]:
arr1 = np.zeros(5, dtype=int)
arr2 = np.ones(5, dtype=int)

In [8]:
np.vstack([arr1, arr2])

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

## Exercise 9. How to stack two arrays horizontally?

In [9]:
np.hstack([arr1, arr2])

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

## Exercise 10. How to generate custom sequences in numpy without hardcoding?

In [16]:
a1 = np.arange(0,10,2)
a1

array([0, 2, 4, 6, 8])

In [17]:
a2 = np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

In [19]:
np.hstack([np.repeat(a1,2), np.tile(a2,2)])

array([0, 0, 2, 2, 4, 4, 6, 6, 8, 8, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9])

## Exercise 11. How to get the common items between two python numpy arrays?

In [3]:
a11 = np.array([1,2,3,4,5])
b11 = np.array([0,2,4,6,8])

In [4]:
np.intersect1d(a11,b11)

array([2, 4])

In [8]:
c11 = np.zeros(10, dtype=int).reshape(2, -1)
d11 = np.ones(10, dtype=int).reshape(1, -1)

In [10]:
np.intersect1d(c11, d11)

array([], dtype=int64)

`.intersect1d(x, y)` it return 1D array of common elements

## Exercise 12. How to remove from one array those items that exist in another?

In [11]:
np.setdiff1d(a11, b11)

array([1, 3, 5])

## Exercise 13. How to get the positions where elements of two arrays match?

In [15]:
z11 = np.array([1,2,3,4,5,6])
y11 = np.array([1,0,3,0,0,6])
np.where(z11==y11)

(array([0, 2, 5]),)

In [18]:
# index of even numbers
np.where(z11%2==0)

(array([1, 3, 5]),)

## Exercise 14. How to extract all numbers between a given range from a numpy array?

In [28]:
a14 = np.arange(12)
# extract 5 to 10
result = a14[(a14>=5) & (a14<=10)]
result

array([ 5,  6,  7,  8,  9, 10])